### ISSUE TITLE
The PX/technical-principles/ link is broken.

### ISSUE THREAD

**Issue by geneberkowitz** [PredixDev/ref-digital-meter#1]
The link "https://github.sw.ge.com/pages/PX/technical-principles/" returns 404/Site not found.
Also, Chrome objects to the cert belonging to GE, rather than GitHub.

**Comment by gstroup** [comment]
Thanks for pointing that out.  It was an old out-of-date link.  I replaced it with a new link, hope that helps!

**Comment by geneberkowitz** [comment]
Much better now, thanks.  Please consider uploading a screenshot of the control in action.

**Comment by gstroup** [comment]
Hi Gene, I uploaded an image now too.  I had been thinking about doing that earlier... thanks for the nudge.
